Repository qlcchain/qlc-go-sdk, pull requests merged in 2020-06, with the labels that each got.

#62 feat: add dod settlement api
  client.go
  dod_settlement_enum.go
  dodbilling.go
  dodsettlement.go
Labels: Priority: Medium, Status: Accepted, Type: Enhancement, ready-to-merge

#64 Feature/dodsettlement
  dodsettlement.go
Labels: Priority: High, Status: Completed, Type: Enhancement, ready-to-rebase-and-merge

#65 fix: update product id by seq
  dodsettlement.go
Labels: Type: Enhancement, ready-to-rebase-and-merge

#66 Fix/update product info
  dodsettlement.go
Labels: ready-to-rebase-and-merge

#67 feat: dod settlement privacy
  dodsettlement.go
Labels: ready-to-rebase-and-merge
